const crypto = require("node:crypto");
const express = require("express");
const MailuGeneratedBatch = require("../models/MailuGeneratedBatch");
const MailuGeneratedUser = require("../models/MailuGeneratedUser");
const MailuCreatedUser = require("../models/MailuCreatedUser");

const router = express.Router();
const MAX_USERS = 10000;
const DEFAULT_DOMAIN = "aitechia.com";
const PROTECTED_LOCAL_PARTS = new Set([
  "abuse",
  "admin",
  "hostmaster",
  "otp",
  "postmaster",
  "webmaster",
]);

function normalizeDomain(value) {
  return String(value || DEFAULT_DOMAIN)
    .trim()
    .toLowerCase()
    .replace(/^@/, "");
}

function normalizeApiPath(apiPath) {
  const cleanPath = String(apiPath || "/api").trim() || "/api";
  return cleanPath.startsWith("/") ? cleanPath.replace(/\/+$/, "") : `/${cleanPath}`;
}

function buildMailuUrl(baseUrl, apiPath, endpoint) {
  const origin = new URL(String(baseUrl || "").trim());
  const cleanApiPath = normalizeApiPath(apiPath);
  origin.pathname = `${origin.pathname.replace(/\/+$/, "")}${cleanApiPath}${endpoint}`;
  origin.search = "";
  origin.hash = "";
  return origin;
}

function validateMailuConfig(config) {
  if (!config.baseUrl) {
    const error = new Error("Mailu URL is required");
    error.statusCode = 400;
    throw error;
  }

  if (!config.apiToken || String(config.apiToken).trim().length < 4) {
    const error = new Error("A valid Mailu API token is required");
    error.statusCode = 400;
    throw error;
  }

  try {
    buildMailuUrl(config.baseUrl, config.apiPath, "/v1/user");
  } catch {
    const error = new Error("Mailu URL is not valid");
    error.statusCode = 400;
    throw error;
  }
}

function validateUsers(users) {
  if (!Array.isArray(users) || users.length === 0) {
    const error = new Error("No generated users were provided");
    error.statusCode = 400;
    throw error;
  }

  if (users.length > MAX_USERS) {
    const error = new Error(`User batch is too large. Maximum is ${MAX_USERS}`);
    error.statusCode = 400;
    throw error;
  }
}

function dedupeUsersByEmail(users) {
  const byEmail = new Map();

  for (const user of users) {
    if (!byEmail.has(user.email)) {
      byEmail.set(user.email, user);
    }
  }

  return [...byEmail.values()];
}

function normalizeGeneratedUser(row, batchId, domain) {
  const email = String(row.email || "").trim().toLowerCase();
  const password = String(row.password || "");
  const name = String(row.name || `${row.firstName || ""} ${row.surname || ""}`).trim();

  if (!email.endsWith(`@${domain}`)) {
    throw new Error(`Email ${email || "(blank)"} must end with @${domain}`);
  }

  if (!password) {
    throw new Error(`Password is missing for ${email}`);
  }

  return {
    batchId,
    domain,
    name,
    firstName: String(row.firstName || "").trim(),
    surname: String(row.surname || "").trim(),
    day: Number(row.day || row.birthDay) || undefined,
    month: Number(row.month || row.birthMonth) || undefined,
    year: Number(row.year || row.birthYear) || undefined,
    gender: String(row.gender || "").trim(),
    email,
    password,
  };
}

function toMailuPayload(user) {
  return {
    email: user.email,
    raw_password: user.password,
    displayed_name: user.name || user.email.split("@")[0],
    enabled: true,
    change_pw_next_login: false,
    enable_imap: true,
    enable_pop: false,
    global_admin: false,
    comment: "Generated by Majic Mailu generator",
  };
}

async function callMailu(config, endpoint, options = {}) {
  const url = buildMailuUrl(config.baseUrl, config.apiPath, endpoint);
  const response = await fetch(url, {
    ...options,
    headers: {
      Authorization: `Bearer ${config.apiToken}`,
      Accept: "application/json",
      ...(options.body ? { "Content-Type": "application/json" } : {}),
      ...(options.headers || {}),
    },
  });
  const text = await response.text();
  let data = {};

  try {
    data = text ? JSON.parse(text) : {};
  } catch {
    data = { message: text };
  }

  return { ok: response.ok, status: response.status, data };
}

function mailuUserEmail(user) {
  if (!user || typeof user !== "object") return "";
  return String(user.email || user.mail || user.username || user.localpart || "").trim().toLowerCase();
}

function mailuUserId(user) {
  if (!user || typeof user !== "object") return "";
  return String(user.id || user.email || user.mail || user.username || "").trim();
}

async function listMailuUsers(config) {
  const result = await callMailu(config, "/v1/user", { method: "GET" });
  if (!result.ok) {
    const error = new Error(result.data.message || `Mailu returned HTTP ${result.status}`);
    error.statusCode = 502;
    throw error;
  }

  return Array.isArray(result.data) ? result.data : [];
}

async function deleteMailuUser(config, user) {
  const id = mailuUserId(user);
  if (!id) {
    return { ok: false, status: 0, data: { message: "Mailu user id/email is missing" } };
  }

  return callMailu(config, `/v1/user/${encodeURIComponent(id)}`, {
    method: "DELETE",
  });
}

function isProtectedEmail(email) {
  const localPart = String(email || "").split("@")[0].toLowerCase();
  return PROTECTED_LOCAL_PARTS.has(localPart);
}

function generatedEmailFirstNameKey(email, domain) {
  const normalized = String(email || "").trim().toLowerCase();
  if (domain && !normalized.endsWith(`@${domain}`)) return "";

  const localPart = normalized.split("@")[0] || "";
  const match = localPart.match(/^([a-z0-9]+)\.[a-z0-9]+\d+$/i);
  return match ? match[1] : "";
}

function groupGeneratedMailuUsersByFirstName(users, domain) {
  const byFirstName = new Map();

  for (const user of users) {
    const email = mailuUserEmail(user);
    const firstNameKey = generatedEmailFirstNameKey(email, domain);
    if (!firstNameKey) continue;
    byFirstName.set(firstNameKey, [...(byFirstName.get(firstNameKey) || []), user]);
  }

  return byFirstName;
}

function uniqueMailuUsers(users) {
  const byId = new Map();

  for (const user of users) {
    const id = mailuUserId(user) || mailuUserEmail(user);
    if (!id || byId.has(id)) continue;
    byId.set(id, user);
  }

  return [...byId.values()];
}

async function saveGeneratedBatch(users, domain, source = "mailu-generator", batchId) {
  validateUsers(users);
  const effectiveBatchId = batchId || crypto.randomUUID();
  const normalizedUsers = dedupeUsersByEmail(
    users.map((user) => normalizeGeneratedUser(user, effectiveBatchId, domain))
  );

  await MailuGeneratedBatch.findOneAndUpdate(
    { batchId: effectiveBatchId },
    {
      $set: {
        batchId: effectiveBatchId,
        domain,
        count: normalizedUsers.length,
        source,
      },
    },
    { new: true, upsert: true }
  );

  await MailuGeneratedUser.bulkWrite(
    normalizedUsers.map((user) => ({
      updateOne: {
        filter: { batchId: effectiveBatchId, email: user.email },
        update: { $set: user },
        upsert: true,
      },
    })),
    { ordered: false }
  );

  return { batchId: effectiveBatchId, users: normalizedUsers };
}

function queryLimit(value, fallback = 100, max = 500) {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(Math.max(parsed, 1), max);
}

router.post("/generated-batches", async (req, res, next) => {
  try {
    const domain = normalizeDomain(req.body.domain);
    const result = await saveGeneratedBatch(
      req.body.users,
      domain,
      req.body.source || "mailu-generator",
      req.body.batchId
    );

    res.json({
      message: `Saved ${result.users.length} generated users to MongoDB`,
      batchId: result.batchId,
      count: result.users.length,
    });
  } catch (error) {
    next(error);
  }
});

router.get("/batches", async (req, res, next) => {
  try {
    const limit = queryLimit(req.query.limit, 50);
    const batches = await MailuGeneratedBatch.find({})
      .sort({ createdAt: -1 })
      .limit(limit)
      .lean();

    res.json({ batches });
  } catch (error) {
    next(error);
  }
});

router.get("/batches/:batchId", async (req, res, next) => {
  try {
    const batch = await MailuGeneratedBatch.findOne({ batchId: req.params.batchId }).lean();
    if (!batch) {
      const error = new Error("Batch not found");
      error.statusCode = 404;
      throw error;
    }

    const [users, mailuResults] = await Promise.all([
      MailuGeneratedUser.find({ batchId: req.params.batchId })
        .sort({ email: 1 })
        .limit(queryLimit(req.query.limit, 500))
        .lean(),
      MailuCreatedUser.find({ batchId: req.params.batchId })
        .sort({ createdAt: -1 })
        .limit(queryLimit(req.query.limit, 500))
        .lean(),
    ]);

    res.json({ batch, users, mailuResults });
  } catch (error) {
    next(error);
  }
});

router.get("/created", async (req, res, next) => {
  try {
    const query = {};
    const search = String(req.query.search || "").trim().toLowerCase();
    if (search) {
      query.email = { $regex: search.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), $options: "i" };
    }
    if (req.query.batchId) query.batchId = String(req.query.batchId);
    if (req.query.status) query.status = String(req.query.status);

    const limit = queryLimit(req.query.limit, 100, 10000);
    const [createdUsers, total] = await Promise.all([
      MailuCreatedUser.find(query)
        .populate("generatedUserId")
        .sort({ createdAt: -1 })
        .limit(limit)
        .lean(),
      MailuCreatedUser.countDocuments(query),
    ]);

    res.json({ createdUsers, total, limit });
  } catch (error) {
    next(error);
  }
});

router.post("/test", async (req, res, next) => {
  try {
    validateMailuConfig(req.body);
    const users = await listMailuUsers(req.body);

    res.json({
      message: "Mailu API connection succeeded",
      summary: { existingUsers: users.length },
    });
  } catch (error) {
    next(error);
  }
});

router.post("/duplicates", async (req, res, next) => {
  try {
    validateMailuConfig(req.body);
    const users = await listMailuUsers(req.body);
    const domain = normalizeDomain(req.body.domain);
    const byEmail = new Map();

    for (const user of users) {
      const email = mailuUserEmail(user);
      if (!email || !email.endsWith(`@${domain}`)) continue;
      byEmail.set(email, [...(byEmail.get(email) || []), user]);
    }

    const duplicates = [...byEmail.entries()]
      .filter(([, entries]) => entries.length > 1)
      .map(([email, entries]) => ({
        email,
        count: entries.length,
        keep: mailuUserId(entries[0]),
        delete: entries.slice(1).map((entry) => mailuUserId(entry)),
      }));

    res.json({
      message: duplicates.length
        ? `Found ${duplicates.length} duplicate Mailu address group(s)`
        : "No duplicate Mailu addresses found",
      summary: {
        existingUsers: users.length,
        duplicateGroups: duplicates.length,
        duplicateUsersToDelete: duplicates.reduce(
          (total, duplicate) => total + duplicate.delete.length,
          0
        ),
      },
      duplicates,
    });
  } catch (error) {
    next(error);
  }
});

router.post("/cleanup-duplicates", async (req, res, next) => {
  try {
    validateMailuConfig(req.body);
    const dryRun = req.body.dryRun !== false;
    const users = await listMailuUsers(req.body);
    const domain = normalizeDomain(req.body.domain);
    const byEmail = new Map();

    for (const user of users) {
      const email = mailuUserEmail(user);
      if (!email || !email.endsWith(`@${domain}`)) continue;
      byEmail.set(email, [...(byEmail.get(email) || []), user]);
    }

    const deletionCandidates = [...byEmail.entries()].flatMap(([email, entries]) =>
      entries.slice(1).map((user) => ({ email, user, id: mailuUserId(user) }))
    );
    const results = [];
    const summary = {
      checked: users.length,
      duplicateUsersFound: deletionCandidates.length,
      deleted: 0,
      failed: 0,
      dryRun: dryRun ? 1 : 0,
    };

    for (const candidate of deletionCandidates) {
      if (dryRun) {
        results.push({
          email: candidate.email,
          id: candidate.id,
          status: "checked",
          message: "Would delete duplicate user",
        });
        continue;
      }

      const deleteResult = await deleteMailuUser(req.body, candidate.user);
      const status = deleteResult.ok ? "deleted" : "failed";
      summary[status] += 1;
      results.push({
        email: candidate.email,
        id: candidate.id,
        status,
        message:
          deleteResult.data.message ||
          (deleteResult.ok ? "Deleted duplicate user" : `Mailu returned HTTP ${deleteResult.status}`),
      });
    }

    res.json({
      message: dryRun
        ? `Dry run found ${summary.duplicateUsersFound} duplicate Mailu user(s) to delete`
        : `Mailu duplicate cleanup finished: ${summary.deleted} deleted, ${summary.failed} failed`,
      summary,
      results,
    });
  } catch (error) {
    next(error);
  }
});

router.post("/cleanup-generated-existing", async (req, res, next) => {
  try {
    validateMailuConfig(req.body);
    const domain = normalizeDomain(req.body.domain);
    const dryRun = req.body.dryRun !== false;
    const normalizedUsers = dedupeUsersByEmail(
      (Array.isArray(req.body.users) ? req.body.users : []).map((user) =>
        normalizeGeneratedUser(user, req.body.batchId || "cleanup", domain)
      )
    );

    if (normalizedUsers.length === 0) {
      const error = new Error("No generated users were provided for cleanup");
      error.statusCode = 400;
      throw error;
    }

    const requestedFirstNameKeys = new Set(
      normalizedUsers
        .map((user) => generatedEmailFirstNameKey(user.email, domain))
        .filter(Boolean)
    );
    const users = await listMailuUsers(req.body);
    const existingByFirstName = groupGeneratedMailuUsersByFirstName(users, domain);
    const requestedPatternUsers = [...requestedFirstNameKeys].flatMap(
      (firstNameKey) => existingByFirstName.get(firstNameKey) || []
    );
    const globalDuplicatePatternUsers = [...existingByFirstName.values()].flatMap(
      (entries) =>
        entries.length > 1
          ? entries.slice().sort((left, right) =>
              mailuUserEmail(left).localeCompare(mailuUserEmail(right))
            )
          : []
    );
    const existingGeneratedUsers = uniqueMailuUsers([
      ...requestedPatternUsers,
      ...globalDuplicatePatternUsers,
    ]);
    const results = [];
    const summary = {
      checked: normalizedUsers.length,
      firstNamePatternsChecked: requestedFirstNameKeys.size,
      duplicateFirstNamePatternsFound: [...existingByFirstName.values()].filter(
        (entries) => entries.length > 1
      ).length,
      existingGeneratedUsers: existingGeneratedUsers.length,
      protected: 0,
      deleted: 0,
      failed: 0,
      dryRun: dryRun ? 1 : 0,
    };

    for (const existing of existingGeneratedUsers) {
      const existingEmail = mailuUserEmail(existing);
      const firstNameKey = generatedEmailFirstNameKey(existingEmail, domain);

      if (isProtectedEmail(existingEmail)) {
        summary.protected += 1;
        results.push({
          email: existingEmail,
          id: mailuUserId(existing),
          status: "protected",
          message: "Skipped protected mailbox",
        });
        continue;
      }

      if (dryRun) {
        results.push({
          email: existingEmail,
          id: mailuUserId(existing),
          status: "checked",
          message: `Would delete generated mailbox matching first-name pattern ${firstNameKey}`,
        });
        continue;
      }

      const deleteResult = await deleteMailuUser(req.body, existing);
      const status = deleteResult.ok ? "deleted" : "failed";
      summary[status] += 1;
      results.push({
        email: existingEmail,
        id: mailuUserId(existing),
        status,
        message:
          deleteResult.data.message ||
          (deleteResult.ok
            ? `Deleted generated mailbox matching first-name pattern ${firstNameKey}`
            : `Mailu returned HTTP ${deleteResult.status}`),
      });
    }

    res.json({
      message: dryRun
        ? `Dry run found ${summary.existingGeneratedUsers} generated Mailu mailbox(es) from ${summary.firstNamePatternsChecked} requested and ${summary.duplicateFirstNamePatternsFound} duplicate first-name pattern(s)`
        : `Generated Mailu mailbox cleanup finished: ${summary.deleted} deleted, ${summary.failed} failed, ${summary.protected} protected`,
      summary,
      results,
    });
  } catch (error) {
    next(error);
  }
});

router.post("/create", async (req, res, next) => {
  try {
    validateMailuConfig(req.body);
    const domain = normalizeDomain(req.body.domain);
    const dryRun = Boolean(req.body.dryRun);
    const saved = await saveGeneratedBatch(
      req.body.users,
      domain,
      "mailu-create",
      req.body.batchId
    );
    const generatedDocs = await MailuGeneratedUser.find({
      batchId: saved.batchId,
      email: { $in: saved.users.map((user) => user.email) },
    }).lean();
    const generatedByEmail = new Map(
      generatedDocs.map((user) => [user.email, user])
    );
    const results = [];
    const summary = { created: 0, skipped: 0, failed: 0, checked: 0, existing: 0 };
    const existingUsers = await listMailuUsers(req.body);
    const existingEmails = new Set(existingUsers.map(mailuUserEmail).filter(Boolean));
    const existingFirstNameKeys = new Set(
      existingUsers
        .map((user) => generatedEmailFirstNameKey(mailuUserEmail(user), domain))
        .filter(Boolean)
    );

    for (const user of saved.users) {
      const generatedDoc = generatedByEmail.get(user.email);
      const firstNameKey = generatedEmailFirstNameKey(user.email, domain);
      const hasExistingPattern = firstNameKey && existingFirstNameKeys.has(firstNameKey);

      if (dryRun) {
        summary.checked += 1;
        if (existingEmails.has(user.email) || hasExistingPattern) summary.existing += 1;
        results.push({
          email: user.email,
          status: "checked",
          message: existingEmails.has(user.email)
            ? "Already exists in Mailu"
            : hasExistingPattern
              ? `Skipped because generated first-name pattern ${firstNameKey} already exists in Mailu`
              : "Ready to create",
        });
        continue;
      }

      let mailuResult;
      if (existingEmails.has(user.email) || hasExistingPattern) {
        mailuResult = {
          ok: false,
          status: 409,
          data: {
            message: existingEmails.has(user.email)
              ? "Skipped because user already exists in Mailu"
              : `Skipped because generated first-name pattern ${firstNameKey} already exists in Mailu`,
          },
        };
      } else {
        try {
          mailuResult = await callMailu(req.body, "/v1/user", {
            method: "POST",
            body: JSON.stringify(toMailuPayload(user)),
          });
        } catch (error) {
          mailuResult = {
            ok: false,
            status: 0,
            data: { message: error.message || "Mailu request failed" },
          };
        }
      }
      const status = mailuResult.ok
        ? "created"
        : mailuResult.status === 409
          ? "skipped"
          : "failed";

      summary[status] += 1;
      if (mailuResult.status === 409) summary.existing += 1;
      if (mailuResult.ok) {
        existingEmails.add(user.email);
        if (firstNameKey) existingFirstNameKeys.add(firstNameKey);
      }

      const result = {
        batchId: saved.batchId,
        generatedUserId: generatedDoc?._id,
        domain,
        email: user.email,
        password: user.password,
        displayedName: user.name || user.email.split("@")[0],
        status,
        message:
          mailuResult.data.message ||
          (mailuResult.ok ? "Created" : `Mailu returned HTTP ${mailuResult.status}`),
        dryRun,
        mailuStatusCode: mailuResult.status,
      };

      await MailuCreatedUser.findOneAndUpdate(
        { batchId: saved.batchId, email: user.email, dryRun },
        { $set: result },
        { new: true, upsert: true }
      );

      results.push({
        email: result.email,
        status: result.status,
        message: result.message,
      });
    }

    if (!dryRun) {
      await MailuGeneratedBatch.findOneAndUpdate(
        { batchId: saved.batchId },
        { $set: { latestMailuSummary: summary } }
      );
    }

    res.json({
      message: dryRun
        ? `Dry run checked ${summary.checked} generated users`
        : `Mailu batch finished: ${summary.created} created, ${summary.skipped} skipped, ${summary.failed} failed`,
      batchId: saved.batchId,
      summary,
      results,
    });
  } catch (error) {
    next(error);
  }
});

module.exports = router;
